import { notFound } from "next/navigation";
import { DocumentPlaceholder } from "@/components";
import { AdminHeader, Button, LinkButton, Panel, RequestIdentity, Status, Table, TableBody, TableCell, TableContainer, TableHead, TableHeader, TableRow, s } from "@/components/admin/admin-ui";
import { inventoryRequests } from "@/lib/mock-data";

export default async function VerificationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const request = inventoryRequests.find((r) => r.id === id) ?? (id === "borrow-005" ? { ...inventoryRequests[0], id, number: "SIPINTER/PMK/VII/2026/00129", borrowerName: "Andi Tenri" } : undefined);
  if (!request) notFound();
  return <><AdminHeader title="Pemeriksaan permohonan" description={request.number} actions={<Status value={request.status} />} /><div className={s.grid7030}><div className={s.stack}><Panel title="Identitas dan kegiatan"><RequestIdentity request={request} /></Panel><Panel title="Barang yang dimohon" flush><TableContainer><Table><TableHead><TableRow><TableHeader>Barang</TableHeader><TableHeader>Jumlah</TableHeader><TableHeader>Stok tersedia</TableHeader><TableHeader>Keputusan</TableHeader></TableRow></TableHead><TableBody>{request.items.map((item) => <TableRow key={item.itemId}><TableCell><strong>{item.itemName}</strong></TableCell><TableCell>{item.quantity} unit</TableCell><TableCell>7 unit</TableCell><TableCell><select className="select" defaultValue="approve"><option value="approve">Sesuai</option><option value="adjust">Sesuaikan jumlah</option><option value="reject">Tidak tersedia</option></select></TableCell></TableRow>)}</TableBody></Table></TableContainer></Panel><Panel title="Dokumen pendukung" description="Buka dokumen dan cocokkan pejabat penandatangan."><div className={s.stack}><DocumentPlaceholder name="Surat_Permohonan_Diskominfo_128.pdf" type="pdf" size={845300} description="Ditandatangani Kepala Dinas · 17 Juli 2026" /><DocumentPlaceholder name="Surat_Tugas_Tim_Sosialisasi.pdf" type="pdf" size={512800} description="7 personel pelaksana" /></div></Panel></div><aside className={s.stack}><Panel title="Checklist verifikator" description="Seluruh butir wajib sebelum diteruskan."><div className={s.checklist}>{["Identitas dan NIP pemohon sesuai", "Surat permohonan sah dan terbaca", "Tujuan penggunaan bersifat kedinasan", "Jadwal tidak bertabrakan", "Jumlah sesuai kebutuhan kegiatan", "Stok fisik telah dikonfirmasi"].map((label, i) => <label className={s.check} key={label}><input type="checkbox" defaultChecked={i < 4} /><span>{label}</span></label>)}</div></Panel><Panel title="Catatan keputusan"><label className="field"><span className="field__label">Catatan untuk pemohon / Sekda *</span><textarea className={s.textarea} placeholder="Wajib diisi untuk permintaan revisi atau penolakan." /></label><p className={s.compact}>Catatan menjadi bagian riwayat permohonan dan tidak dapat dihapus setelah keputusan dikirim.</p><div className={s.actions}><Button variant="danger">Tolak</Button><Button variant="outline">Minta revisi</Button><Button>Teruskan ke Sekda</Button></div></Panel></aside></div><div className={s.stickyActions}><LinkButton href="/admin/verifikasi" secondary>Kembali ke antrean</LinkButton><span className={s.compact}>Checklist belum lengkap: 2 butir</span><Button disabled>Teruskan permohonan</Button></div></>;
}
