import { BorrowingStatus, Role } from "@prisma/client";
import { AdminHeader, Panel, Status, Table, TableBody, TableCell, TableContainer, TableHead, TableHeader, TableRow, formatDate, s } from "@/components/admin/admin-ui";
import { ReportActions } from "@/components/admin/report-actions";
import { requireRole } from "@/lib/auth";
import { db } from "@/lib/db";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const [, params] = await Promise.all([requireRole([Role.ADMIN]), searchParams]);
  const status = Object.values(BorrowingStatus).includes(params.status as BorrowingStatus) ? params.status as BorrowingStatus : undefined;
  const requests = await db.borrowingRequest.findMany({ where: status ? { status } : {}, include: { borrower: { include: { skpd: true } }, items: { include: { item: true } } }, orderBy: { createdAt: "desc" }, take: 500 });
  const rows: Array<Array<string | number>> = [["Nomor", "Peminjam", "SKPD", "Keperluan", "Mulai", "Selesai", "Kendaraan", "Status"], ...requests.map((request) => [request.registrationNumber, request.borrower.name, request.borrower.skpd.name, request.purpose, request.borrowDate.toISOString().slice(0, 10), request.plannedReturnDate.toISOString().slice(0, 10), request.items.map((entry) => `${entry.item.name} ${entry.item.registrationNumber ?? entry.item.itemCode}`).join("; "), request.status])];
  return <><AdminHeader title="Laporan peminjaman kendaraan" description="Rekap transaksi berdasarkan data operasional SIPINTER." actions={<ReportActions rows={rows} />} /><form className="filter-bar" method="get"><select className="select" name="status" defaultValue={status ?? ""} aria-label="Status transaksi"><option value="">Semua status</option>{Object.values(BorrowingStatus).map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><button className="button button--outline" type="submit">Tampilkan</button></form><Panel title="Rekap transaksi" description={`${requests.length} transaksi ditampilkan`} flush><TableContainer><Table><TableHead><TableRow><TableHeader>Nomor</TableHeader><TableHeader>Peminjam / SKPD</TableHeader><TableHeader>Keperluan</TableHeader><TableHeader>Periode</TableHeader><TableHeader>Kendaraan</TableHeader><TableHeader>Status</TableHeader></TableRow></TableHead><TableBody>{requests.map((request) => <TableRow key={request.id}><TableCell><strong className={s.mono}>{request.registrationNumber}</strong></TableCell><TableCell><strong>{request.borrower.name}</strong><div className={s.compact}>{request.borrower.skpd.name}</div></TableCell><TableCell>{request.purpose}</TableCell><TableCell>{formatDate(request.borrowDate, "dd MMM")} - {formatDate(request.plannedReturnDate, "dd MMM yyyy")}</TableCell><TableCell>{request.items.map((entry) => <div key={entry.id}>{entry.item.name} · {entry.item.registrationNumber ?? entry.item.itemCode}</div>)}</TableCell><TableCell><Status value={request.status} /></TableCell></TableRow>)}</TableBody></Table></TableContainer>{!requests.length && <p className={s.empty}>Tidak ada transaksi pada filter ini.</p>}</Panel></>;
}
